[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--no-audit --no-fund"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@netlify/functions"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = """
      default-src 'self' 'unsafe-inline' 'unsafe-eval' data: *.netlify.app netlify.app *.pinterest.com *.googleapis.com identitytoolkit.googleapis.com;
      img-src 'self' data: blob: https:;
      connect-src 'self' data: *.netlify.app netlify.app *.pinterest.com *.firebaseio.com *.googleapis.com identitytoolkit.googleapis.com;
      script-src 'self' 'unsafe-inline' 'unsafe-eval' *.googleapis.com;
      frame-src *.googleapis.com;
      style-src 'self' 'unsafe-inline';
      font-src 'self' data:;
    """

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/*.css"
  [headers.values]
    Content-Type = "text/css"